In [1]:
import pandas as pd

In [2]:
caminho = '../arquivos/vendas_loja.csv'

In [5]:
df = pd.read_csv(caminho, sep=';', decimal=',')

In [7]:
df.head()

,data,produto,categoria,quantidade,preco_unitario,valor_total
0,2025-07-30,Fone de Ouvido,Periféricos,4,4589.94,18359.76
1,2025-07-08,Laptop,Eletrônicos,4,3526.15,14104.60
2,2025-06-01,Fone de Ouvido,Periféricos,3,1068.22,3204.66
3,2025-06-28,Fone de Ouvido,Periféricos,2,933.85,1867.70
4,2025-07-21,SSD Externo,Periféricos,3,2390.20,7170.60

Exercício 1: Filtrar por Valor Numérico
<br>
Objetivo: Selecionar e mostrar apenas as vendas com Valor superior a R$ 1.000,00.

In [11]:
df[df['valor_total']>1000].sort_values(by='valor_total',ascending=False).head()

,data,produto,categoria,quantidade,preco_unitario,valor_total
9,2025-05-30,Laptop,Eletrônicos,4,4917.07,19668.28
40,2025-07-29,Fone de Ouvido,Periféricos,4,4887.10,19548.40
14,2025-07-08,Tablet,Eletrônicos,4,4698.11,18792.44
0,2025-07-30,Fone de Ouvido,Periféricos,4,4589.94,18359.76
83,2025-06-16,Webcam,Periféricos,4,4587.57,18350.28

Exercício 2: Filtrar por Texto Exato
<br>
Objetivo: Selecionar e mostrar todas as vendas do produto Celular.

In [12]:
df['produto'].unique()

array(['Fone de Ouvido', 'Laptop', 'SSD Externo', 'Smartphone',
       'Carregador', 'Mesa de Escritório', 'Tablet', 'Cadeira Gamer',
       'Mouse', 'Teclado', 'Caixa de Som', 'Monitor', 'Impressora',
       'Webcam', 'HD Externo'], dtype=object)

In [20]:
df[df['produto'] == 'Smartphone']

,data,produto,categoria,quantidade,preco_unitario,valor_total
5,2025-05-13,Smartphone,Eletrônicos,1,488.57,488.57
18,2025-07-31,Smartphone,Eletrônicos,1,3442.05,3442.05
39,2025-05-21,Smartphone,Eletrônicos,2,1244.79,2489.58
54,2025-06-17,Smartphone,Eletrônicos,2,195.79,391.58
61,2025-07-17,Smartphone,Eletrônicos,2,1868.38,3736.76
99,2025-06-07,Smartphone,Eletrônicos,2,4147.16,8294.32

Exercício 3: Filtrar Múltiplas Condições (OU)
<br>
Objetivo: Selecionar as vendas em que a Quantidade é maior que 3 OU o Produto é Laptop.

In [27]:
df[(df['quantidade'] > 3) | (df['produto'] == 'Laptop')]

,data,produto,categoria,quantidade,preco_unitario,valor_total
0,2025-07-30,Fone de Ouvido,Periféricos,4,4589.94,18359.76
1,2025-07-08,Laptop,Eletrônicos,4,3526.15,14104.60
7,2025-06-21,Laptop,Eletrônicos,1,4607.33,4607.33
8,2025-06-27,Laptop,Eletrônicos,2,4914.51,9829.02
9,2025-05-30,Laptop,Eletrônicos,4,4917.07,19668.28
12,2025-06-19,Laptop,Eletrônicos,3,1314.19,3942.57
14,2025-07-08,Tablet,Eletrônicos,4,4698.11,18792.44
21,2025-08-04,Tablet,Eletrônicos,4,99.60,398.40
23,2025-05-30,Caixa de Som,Periféricos,4,4255.68,17022.72
25,2025-07-07,Laptop,Eletrônicos,3,2964.93,8894.79
30,2025-07-12,Laptop,Eletrônicos,2,4685.30,9370.60
32,2025-07-27,Webcam,Periféricos,4,2869.56,11478.24
33,2025-06-26,Fone de Ouvido,Periféricos,4,3052.85,12211.40
35,2025-07-13,Caixa de Som,Periféricos,4,1513.75,6055.00
38,2025-08-01,Tablet,Eletrônicos,4,281.27,1125.08
40,2025-07-29,Fone de Ouvido,Periféricos,4,4887.10,19548.40
42,2025-06-12,Caixa de Som,Periféricos,4,81.34,325.36
43,2025-05-10,Mouse,Periféricos,4,1319.67,5278.68
49,2025-07-29,Laptop,Eletrônicos,4,3644.61,14578.44
56,2025-06-20,Laptop,Eletrônicos,2,3162.65,6325.30
65,2025-07-14,Impressora,Eletrônicos,4,351.39,1405.56
68,2025-06-25,Mesa de Escritório,Móveis,4,710.68,2842.72
72,2025-06-27,Cadeira Gamer,Móveis,4,613.47,2453.88
73,2025-06-03,Monitor,Eletrônicos,4,2021.12,8084.48
74,2025-06-07,Laptop,Eletrônicos,1,4320.94,4320.94
75,2025-07-09,Laptop,Eletrônicos,3,2093.86,6281.58
77,2025-07-13,Webcam,Periféricos,4,4364.12,17456.48
83,2025-06-16,Webcam,Periféricos,4,4587.57,18350.28
84,2025-06-15,Monitor,Eletrônicos,4,3235.78,12943.12
92,2025-05-22,SSD Externo,Periféricos,4,4025.49,16101.96

Exercício 5: Filtrar usando .isin()
<br>
Objetivo: Selecionar todas as vendas dos produtos Mouse ou Teclado de uma só vez.
<br>
(Dica: o método .isin() é usado para verificar se o valor de uma coluna está contido em uma lista).

In [28]:
df[df['produto'].isin(['Mouse', 'Teclado'])]

          data  produto    categoria  quantidade  preco_unitario  valor_total
19  2025-07-29    Mouse  Periféricos           3         1429.57      4288.71
20  2025-07-22    Mouse  Periféricos           1         1226.20      1226.20
22  2025-07-25  Teclado  Periféricos           3         4425.78     13277.34
43  2025-05-10    Mouse  Periféricos           4         1319.67      5278.68
47  2025-06-26    Mouse  Periféricos           3         2074.33      6222.99
53  2025-07-03  Teclado  Periféricos           2         1727.62      3455.24
63  2025-06-15    Mouse  Periféricos           2          383.27       766.54
85  2025-06-20    Mouse  Periféricos           3         4215.71     12647.13
89  2025-06-01    Mouse  Periféricos           2          668.68      1337.36
95  2025-05-10  Teclado  Periféricos           3           81.19       243.57
97  2025-06-05  Teclado  Periféricos           3         1298.77      3896.31
98  2025-07-22  Teclado  Periféricos           2          123.59       247.18