In [283]:
import requests
import json
import pandas as pd
import os

In [284]:
qtd_users = 10
format = 'json'
url = f'https://randomuser.me/api/?results={qtd_users}&format={format}'

In [285]:
response = requests.get(url)
dados = response.json()

In [ ]:
print(json.dumps(dados, indent=3))

In [287]:
dados['results'][0]['name']['first']

'Ronja'

In [288]:
df = pd.json_normalize(dados['results'])
df

,gender,email,phone,cell,nat,name.title,name.first,name.last,location.street.number,location.street.name,...,login.sha256,dob.date,dob.age,registered.date,registered.age,id.name,id.value,picture.large,picture.medium,picture.thumbnail
0,female,ronja.perala@example.com,02-019-178,043-419-15-21,FI,Miss,Ronja,Perala,4324,Fredrikinkatu,...,4346a1ba8e3f1d32ac4bdc2bf3c73de1d2d608b51eb2ed...,1973-01-06T05:13:06.723Z,52,2012-12-14T15:43:38.420Z,12,HETU,NaNNA288undefined,https://randomuser.me/api/portraits/women/63.jpg,https://randomuser.me/api/portraits/med/women/...,https://randomuser.me/api/portraits/thumb/wome...
1,male,valentin.delgado@example.com,(603) 089 4075,(662) 762 8736,MX,Mr,Valentin,Delgado,1281,Circuito Norte Haro,...,c4dc0a0add53f631b64de0bcbd39572c080f0f8023c00d...,1950-09-29T17:48:13.328Z,74,2004-06-12T15:52:08.268Z,21,NSS,85 47 12 1933 7,https://randomuser.me/api/portraits/men/95.jpg,https://randomuser.me/api/portraits/med/men/95...,https://randomuser.me/api/portraits/thumb/men/...
2,male,ivan.frostad@example.com,85369748,47133313,NO,Mr,Ivan,Frostad,7805,Høydalsveien,...,23093e9e3a6c8acedc7e67d1568a217fbbdb53e48e0e5b...,1988-01-11T21:48:06.891Z,37,2002-04-22T18:00:51.317Z,23,FN,11018810117,https://randomuser.me/api/portraits/men/40.jpg,https://randomuser.me/api/portraits/med/men/40...,https://randomuser.me/api/portraits/thumb/men/...
3,male,keith.garcia@example.com,08-7423-3448,0499-549-408,AU,Mr,Keith,Garcia,7852,Hickory Creek Dr,...,e50d2e6b0384ac0bd773400c779171ba6203155a070826...,1946-02-15T07:41:16.687Z,79,2017-09-05T15:06:03.266Z,7,TFN,430715429,https://randomuser.me/api/portraits/men/91.jpg,https://randomuser.me/api/portraits/med/men/91...,https://randomuser.me/api/portraits/thumb/men/...
4,female,akshatha.kavser@example.com,9089322396,9433293330,IN,Mrs,Akshatha,Kavser,6695,Bandstand Promenade,...,016fb527e08fb60f354c01f294528631cd96d1c9ba441f...,1999-12-12T05:04:19.764Z,25,2003-03-11T14:45:57.833Z,22,UIDAI,476819490131,https://randomuser.me/api/portraits/women/9.jpg,https://randomuser.me/api/portraits/med/women/...,https://randomuser.me/api/portraits/thumb/wome...
5,male,tinius.rolland@example.com,56679176,91924075,NO,Mr,Tinius,Rolland,3182,Lille Grensen,...,765ac64d2e513fe78adfd54de5e557eebb4ae915835982...,1972-06-04T06:27:12.283Z,53,2013-10-14T06:26:56.348Z,11,FN,04067246514,https://randomuser.me/api/portraits/men/16.jpg,https://randomuser.me/api/portraits/med/men/16...,https://randomuser.me/api/portraits/thumb/men/...
6,male,christer.ostrem@example.com,80928231,97472648,NO,Mr,Christer,Østrem,5535,Grønsundveien,...,e0549af4a694c3623cc7128d0910b438601ffb2460a8bd...,1992-06-04T10:34:14.728Z,33,2014-11-17T20:19:37.920Z,10,FN,04069221578,https://randomuser.me/api/portraits/men/5.jpg,https://randomuser.me/api/portraits/med/men/5.jpg,https://randomuser.me/api/portraits/thumb/men/...
7,male,charles.chan@example.com,P87 W88-5211,O13 X27-8210,CA,Mr,Charles,Chan,1110,King St,...,0f5b71cdb789dcddd90af7109dfb427f5e253e26528440...,1968-12-24T00:07:29.704Z,56,2022-02-23T08:05:44.315Z,3,SIN,363309675,https://randomuser.me/api/portraits/men/52.jpg,https://randomuser.me/api/portraits/med/men/52...,https://randomuser.me/api/portraits/thumb/men/...
8,male,noe.guillot@example.com,05-88-39-72-89,06-40-14-21-80,FR,Mr,Noe,Guillot,7503,Boulevard de la Duchère,...,4480e8d2b9255ec62f7b8ce0aa809f0ff350ee49c180a7...,1969-02-12T17:59:37.148Z,56,2006-09-01T17:28:21.243Z,18,INSEE,1690139907864 50,https://randomuser.me/api/portraits/men/7.jpg,https://randomuser.me/api/portraits/med/men/7.jpg,https://randomuser.me/api/portraits/thumb/men/...
9,male,alexandre.taylor@example.com,R80 V96-4840,S41 F03-3166,CA,Mr,Alexandre,Taylor,2025,Concession Road 23,...,4ab91ae8ad2c35c4cc20bc19473994aeaea5102d2a4015...,1989-10-15T23:50:06.476Z,35,2015-05-03T07:13:02.824Z,10,SIN,310250493,https://randomuser.me/api/portraits/men/14.jpg,https://randomuser.me/api/portraits/med/men/14...,https://randomuser.me/api/portraits/thumb/men/...

In [289]:
df.columns

Index(['gender', 'email', 'phone', 'cell', 'nat', 'name.title', 'name.first',
       'name.last', 'location.street.number', 'location.street.name',
       'location.city', 'location.state', 'location.country',
       'location.postcode', 'location.coordinates.latitude',
       'location.coordinates.longitude', 'location.timezone.offset',
       'location.timezone.description', 'login.uuid', 'login.username',
       'login.password', 'login.salt', 'login.md5', 'login.sha1',
       'login.sha256', 'dob.date', 'dob.age', 'registered.date',
       'registered.age', 'id.name', 'id.value', 'picture.large',
       'picture.medium', 'picture.thumbnail'],
      dtype='object')

In [290]:
df.drop(columns=[
       'location.coordinates.latitude',
       'location.coordinates.longitude', 
       'location.timezone.offset',
       'location.timezone.description', 
       'login.uuid', 
       'login.salt', 
       'login.md5', 
       'login.sha1',
       'login.sha256', 
       'dob.date', 
       'registered.age', 
       'registered.date',
       'id.name', 
       'id.value'
       ], 
       inplace=True)

In [291]:
for i in df.columns:
    print(i)

gender
email
phone
cell
nat
name.title
name.first
name.last
location.street.number
location.street.name
location.city
location.state
location.country
location.postcode
login.username
login.password
dob.age
picture.large
picture.medium
picture.thumbnail

In [292]:
df.rename(columns={'gender': 'Gênero',
                   'phone': 'Telefone',
                   'cell': 'Celular',
                   'nat': 'Naturalidade',
                   'name.title': 'Prefixo',
                   'name.first': 'Primeiro_Nome', 
                   'name.last': 'Último_Nome', 
                   'location.street.number': 'N°',
                   'location.street.name': 'Rua',
                   'location.city': 'Cidade',
                   'location.state': 'Estado',
                   'location.country': 'País',
                   'location.postcode': 'Cod_Postal',
                   'login.username': 'Username',
                   'login.password': 'Senha',
                   'dob.age': 'Idade',
                   'picture.large': 'Foto_Grande',
                   'picture.medium': 'Foto_Média',
                   'picture.thumbnail': 'Thumbnail'
                   },
                   inplace=True)

In [293]:
for i in df.columns:
    print(i)

Gênero
email
Telefone
Celular
Naturalidade
Prefixo
Primeiro_Nome
Último_Nome
N°
Rua
Cidade
Estado
País
Cod_Postal
Username
Senha
Idade
Foto_Grande
Foto_Média
Thumbnail

In [294]:
path = 'relatorio.xlsx'

if os.path.exists(path):
    df_existente = pd.read_excel(path)
    novos_dados = df[~df['Username'].isin(df_existente['Username'])]
    df_final = pd.concat([df_existente, novos_dados], ignore_index=True)
else:
    df_final = df

df_final.to_excel(path, index=False)

In [295]:
path = 'relatorio.xlsx'
df_existente = pd.read_excel(path)
novos_dados = df[df['Username'].isin(df_existente['Username'])]
novos_dados

,Gênero,email,Telefone,Celular,Naturalidade,Prefixo,Primeiro_Nome,Último_Nome,N°,Rua,Cidade,Estado,País,Cod_Postal,Username,Senha,Idade,Foto_Grande,Foto_Média,Thumbnail
0,female,ronja.perala@example.com,02-019-178,043-419-15-21,FI,Miss,Ronja,Perala,4324,Fredrikinkatu,Parkano,Southern Ostrobothnia,Finland,90059,beautifulcat136,temp123,52,https://randomuser.me/api/portraits/women/63.jpg,https://randomuser.me/api/portraits/med/women/...,https://randomuser.me/api/portraits/thumb/wome...
1,male,valentin.delgado@example.com,(603) 089 4075,(662) 762 8736,MX,Mr,Valentin,Delgado,1281,Circuito Norte Haro,Club de Golf Santa Anita,San Luis Potosí,Mexico,59437,organicgorilla622,catnip,74,https://randomuser.me/api/portraits/men/95.jpg,https://randomuser.me/api/portraits/med/men/95...,https://randomuser.me/api/portraits/thumb/men/...
2,male,ivan.frostad@example.com,85369748,47133313,NO,Mr,Ivan,Frostad,7805,Høydalsveien,Frekhaug,Vest-Agder,Norway,3252,yellowmouse744,beta,37,https://randomuser.me/api/portraits/men/40.jpg,https://randomuser.me/api/portraits/med/men/40...,https://randomuser.me/api/portraits/thumb/men/...
3,male,keith.garcia@example.com,08-7423-3448,0499-549-408,AU,Mr,Keith,Garcia,7852,Hickory Creek Dr,Australian Capital Territory,Australian Capital Territory,Australia,7621,goldenrabbit226,sparta,79,https://randomuser.me/api/portraits/men/91.jpg,https://randomuser.me/api/portraits/med/men/91...,https://randomuser.me/api/portraits/thumb/men/...
4,female,akshatha.kavser@example.com,9089322396,9433293330,IN,Mrs,Akshatha,Kavser,6695,Bandstand Promenade,Imphal,Sikkim,India,85189,goldenfish392,delta,25,https://randomuser.me/api/portraits/women/9.jpg,https://randomuser.me/api/portraits/med/women/...,https://randomuser.me/api/portraits/thumb/wome...
5,male,tinius.rolland@example.com,56679176,91924075,NO,Mr,Tinius,Rolland,3182,Lille Grensen,Åsen,Buskerud,Norway,1605,lazyleopard239,mamas,53,https://randomuser.me/api/portraits/men/16.jpg,https://randomuser.me/api/portraits/med/men/16...,https://randomuser.me/api/portraits/thumb/men/...
6,male,christer.ostrem@example.com,80928231,97472648,NO,Mr,Christer,Østrem,5535,Grønsundveien,Melbu,Sør-Trøndelag,Norway,2917,lazyostrich491,light,33,https://randomuser.me/api/portraits/men/5.jpg,https://randomuser.me/api/portraits/med/men/5.jpg,https://randomuser.me/api/portraits/thumb/men/...
7,male,charles.chan@example.com,P87 W88-5211,O13 X27-8210,CA,Mr,Charles,Chan,1110,King St,Deer Lake,Québec,Canada,O0I 3N0,sadladybug167,fearless,56,https://randomuser.me/api/portraits/men/52.jpg,https://randomuser.me/api/portraits/med/men/52...,https://randomuser.me/api/portraits/thumb/men/...
8,male,noe.guillot@example.com,05-88-39-72-89,06-40-14-21-80,FR,Mr,Noe,Guillot,7503,Boulevard de la Duchère,Strasbourg,Cantal,France,40560,greenfrog543,iawgk2,56,https://randomuser.me/api/portraits/men/7.jpg,https://randomuser.me/api/portraits/med/men/7.jpg,https://randomuser.me/api/portraits/thumb/men/...
9,male,alexandre.taylor@example.com,R80 V96-4840,S41 F03-3166,CA,Mr,Alexandre,Taylor,2025,Concession Road 23,Shelbourne,Yukon,Canada,B5Z 9X7,angryostrich111,waffle,35,https://randomuser.me/api/portraits/men/14.jpg,https://randomuser.me/api/portraits/med/men/14...,https://randomuser.me/api/portraits/thumb/men/...

In [302]:
len(df_final)

20